services:

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - rabbit-network
      
  auctiochain:
    image: auctiochain
    build:
      context: .
      dockerfile: AuctioChain/Dockerfile
    ports:
      - 8080:8080
    networks:
      - rabbit-network
    volumes:
      - auctio-chain-app:/data/auctiochainapp
    depends_on:
      - rabbitmq

networks:
  postgres-network:
    driver: bridge
  rabbit-network:
    driver: bridge
  stack: {}
      
volumes:
  auctio-chain-app:
  postgres-data:

